### PR TITLE
Added getImage and update README

### PR DESCRIPTION
**Pull request by BMXsanko**
I added a function to get the image from the API - It returns a Uint8List which can be used by Image.memory(), MemoryImage() in Flutter. You can provide it with a Spotify image uri "spotify:image:theImageUri" or you can use the imageLinkToURi method to convert an image link provided by the Web api to a spotify uri.

### CODE REVIEW

**Comment by Joran-Dob** [comment]
Hi @BMXsanko, I looked at your commit, and I have a question about this new function. So this function gets an image by URL from the Spotify API? 

If so is it may be a nice idea to change this implementation to be done in Dart as that saves a lot of resources. Or at least make it possible to get the currently playing songs thumbnail?

Thanks for your awesome work!

**Comment by BMXsanko** [comment]
Hi @Joran-Dob, It gets the image by a Spotify image ID not URL, for example:
`SpotifyPlayback.getImage("spotify:image:3269971d34d3f17f16efc2dfa95e302cc961a36c");`

You can get the ID of the currently playing track from the player-state(when it gets implemented), then you just pass in the ID for the image. The player state returns the `Track` object from which has the image ID.
image

But if you want I can create a separate function called getCurrentlyPlayingImage() or something.
But I would also like to keep the getImage() function, I implemented it this way because this way you can pass in the image ID from more sources. 
That is why I also made the `imageLinkToURi()` function, it converts a URL provided by the Spotify web API and converts it into a more usable image ID. 
I think I will rename these functions to make them easier to understand.

**Comment by Joran-Dob** [comment]
Hi @BMXsanko! Ok, thanks for clarifying, this looks awesome! I will merge the pull request. And will look at the implementation of getting the current Track from the playerstate.

**Review by Joran-Dob — APPROVED** [review]
Looks good, thanks! 😄

**Pull request merged**
